# setup-secrets.ps1
#
# Run ONCE to encrypt your secrets (CF Access + Orthanc password) with DPAPI.
# The resulting config.secrets.dpapi.json file can ONLY be used by your
# current Windows account, on THIS machine. If you change machine or Windows
# session, run this script again.
#
# No dependency, no module to install: uses the native Windows APIs
# (DPAPI through ConvertFrom-SecureString -> Data Protection API).

$ErrorActionPreference = 'Stop'

$scriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Path
$secretsPath = Join-Path $scriptDir 'config.secrets.dpapi.json'

Write-Host ''
Write-Host '=== DPAPI secrets setup ===' -ForegroundColor Cyan
Write-Host "Target: $secretsPath"
Write-Host ''
Write-Host 'These secrets will be encrypted with your Windows user DPAPI key.'
Write-Host 'Nobody else (another user / another machine) will be able to decrypt them.'
Write-Host ''

if (Test-Path $secretsPath) {
    $resp = Read-Host "The file already exists. Overwrite it? (y/N)"
    if ($resp -notmatch '^[oOyY]') {
        Write-Host 'Aborted.' -ForegroundColor Yellow
        exit 0
    }
}

function Get-Fingerprint {
    # Shows the length + first 4 + last 4 characters.
    # Enough to recognise "that is indeed the one I meant to type"
    # without exposing the whole secret in the terminal/history.
    param([string]$Plain)
    if ([string]::IsNullOrEmpty($Plain)) { return '(empty)' }
    $len = $Plain.Length
    if ($len -le 8) { return "length=$len, content hidden (too short for a fingerprint)" }
    $first = $Plain.Substring(0, 4)
    $last  = $Plain.Substring($len - 4, 4)
    return "length=$len, start=$first... end=...$last"
}

function Read-SecretAndEncrypt {
    param([string]$Label, [switch]$AllowEmpty)
    while ($true) {
        Write-Host ''
        Write-Host "$Label" -ForegroundColor Yellow -NoNewline
        Write-Host ' : ' -NoNewline
        $secure = Read-Host -AsSecureString
        if ($secure.Length -eq 0) {
            if ($AllowEmpty) {
                Write-Host '  -> empty, skipped' -ForegroundColor DarkGray
                return $null
            }
            Write-Host '  -> empty, try again (Ctrl+C to abort)' -ForegroundColor Red
            continue
        }
        # Extract the plain text again to show the fingerprint
        $cred = New-Object System.Management.Automation.PSCredential('x', $secure)
        $plain = $cred.GetNetworkCredential().Password
        $fp = Get-Fingerprint $plain
        Write-Host "  Fingerprint: $fp" -ForegroundColor Cyan
        $resp = Read-Host '  Is that what you meant to type? (y/N)'
        if ($resp -match '^[oOyY]') {
            # ConvertFrom-SecureString without -Key uses DPAPI (CurrentUser scope)
            return ConvertFrom-SecureString -SecureString $secure
        }
        Write-Host '  -> entering this value again' -ForegroundColor Yellow
    }
}

$encOrthancPwd = Read-SecretAndEncrypt 'Orthanc password (press Enter to leave empty, auth_basic inactive)' -AllowEmpty
$encCfId       = Read-SecretAndEncrypt 'CF-Access-Client-Id'
$encCfSecret   = Read-SecretAndEncrypt 'CF-Access-Client-Secret'

$payload = [ordered]@{
    '_doc'             = 'DPAPI-encrypted secrets. Generated by setup-secrets.ps1. Do NOT edit by hand. Re-run setup-secrets.ps1 to regenerate.'
    'orthancPassword'  = $encOrthancPwd
    'cfAccessClientId' = $encCfId
    'cfAccessClientSecret' = $encCfSecret
}

$payload | ConvertTo-Json -Depth 3 | Out-File -FilePath $secretsPath -Encoding UTF8

# ACL: read-only for the owner (defence in depth; DPAPI is technically enough,
# but no point exposing the file to the other local users)
try {
    $acl = Get-Acl $secretsPath
    $acl.SetAccessRuleProtection($true, $false)   # disable inheritance
    $owner = New-Object System.Security.Principal.NTAccount($env:USERDOMAIN, $env:USERNAME)
    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        $owner, 'Read,Write', 'Allow'
    )
    $acl.SetAccessRule($rule)
    Set-Acl -Path $secretsPath -AclObject $acl
    Write-Host "ACL: read-only for $($env:USERDOMAIN)\$($env:USERNAME)" -ForegroundColor DarkGray
} catch {
    Write-Host "(Could not harden the ACL, not a problem: $($_.Exception.Message))" -ForegroundColor DarkGray
}

Write-Host ''
Write-Host "OK -> $secretsPath" -ForegroundColor Green
Write-Host ''
Write-Host 'You can now delete these fields from config.json:' -ForegroundColor Yellow
Write-Host '  orthancPassword, cfAccessClientId, cfAccessClientSecret'
Write-Host '(import-dicom.ps1 reads the encrypted versions from config.secrets.dpapi.json)'
Write-Host ''
