# setup-secrets.ps1
#
# A lancer UNE FOIS pour chiffrer tes secrets (CF Access + mot de passe Orthanc)
# via DPAPI. Le fichier resultant config.secrets.dpapi.json ne sera utilisable
# QUE par ton compte Windows actuel et sur CE poste. Si tu changes de poste ou
# de session Windows, il faudra relancer ce script.
#
# Pas de dependance, pas de module a installer: utilise les APIs Windows natives
# (DPAPI via ConvertFrom-SecureString -> Data Protection API).

$ErrorActionPreference = 'Stop'

$scriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Path
$secretsPath = Join-Path $scriptDir 'config.secrets.dpapi.json'

Write-Host ''
Write-Host '=== Setup secrets DPAPI ===' -ForegroundColor Cyan
Write-Host "Cible: $secretsPath"
Write-Host ''
Write-Host 'Ces secrets seront chiffres avec ta cle DPAPI utilisateur Windows.'
Write-Host 'Personne d''autre (autre user / autre poste) ne pourra les dechiffrer.'
Write-Host ''

if (Test-Path $secretsPath) {
    $resp = Read-Host "Le fichier existe deja. L'ecraser ? (o/N)"
    if ($resp -notmatch '^[oOyY]') {
        Write-Host 'Abandonne.' -ForegroundColor Yellow
        exit 0
    }
}

function Get-Fingerprint {
    # Affiche longueur + 4 premiers + 4 derniers caracteres.
    # Suffisant pour reconnaitre "c'est bien celui que j'ai voulu taper"
    # sans exposer le secret entier dans le terminal/historique.
    param([string]$Plain)
    if ([string]::IsNullOrEmpty($Plain)) { return '(vide)' }
    $len = $Plain.Length
    if ($len -le 8) { return "longueur=$len, contenu masque (trop court pour fingerprint)" }
    $first = $Plain.Substring(0, 4)
    $last  = $Plain.Substring($len - 4, 4)
    return "longueur=$len, debut=$first... fin=...$last"
}

function Read-SecretAndEncrypt {
    param([string]$Label, [switch]$AllowEmpty)
    while ($true) {
        Write-Host ''
        Write-Host "$Label" -ForegroundColor Yellow -NoNewline
        Write-Host ' : ' -NoNewline
        $secure = Read-Host -AsSecureString
        if ($secure.Length -eq 0) {
            if ($AllowEmpty) {
                Write-Host '  -> vide, ignore' -ForegroundColor DarkGray
                return $null
            }
            Write-Host '  -> vide, on recommence (Ctrl+C pour abandonner)' -ForegroundColor Red
            continue
        }
        # Re-extraire le plain-text pour montrer le fingerprint
        $cred = New-Object System.Management.Automation.PSCredential('x', $secure)
        $plain = $cred.GetNetworkCredential().Password
        $fp = Get-Fingerprint $plain
        Write-Host "  Fingerprint: $fp" -ForegroundColor Cyan
        $resp = Read-Host '  C''est bien ce que tu voulais saisir ? (o/N)'
        if ($resp -match '^[oOyY]') {
            # ConvertFrom-SecureString sans -Key utilise DPAPI (CurrentUser scope)
            return ConvertFrom-SecureString -SecureString $secure
        }
        Write-Host '  -> on recommence cette valeur' -ForegroundColor Yellow
    }
}

$encOrthancPwd = Read-SecretAndEncrypt 'Mot de passe Orthanc (Entree directe pour laisser vide, auth_basic inactif)' -AllowEmpty
$encCfId       = Read-SecretAndEncrypt 'CF-Access-Client-Id'
$encCfSecret   = Read-SecretAndEncrypt 'CF-Access-Client-Secret'

$payload = [ordered]@{
    '_doc'             = 'DPAPI-encrypted secrets. Generated by setup-secrets.ps1. Do NOT edit by hand. Re-run setup-secrets.ps1 to regenerate.'
    'orthancPassword'  = $encOrthancPwd
    'cfAccessClientId' = $encCfId
    'cfAccessClientSecret' = $encCfSecret
}

$payload | ConvertTo-Json -Depth 3 | Out-File -FilePath $secretsPath -Encoding UTF8

# ACL: lecture seule pour le proprietaire (defense en profondeur, DPAPI suffit
# techniquement mais autant pas exposer le fichier aux autres users locaux)
try {
    $acl = Get-Acl $secretsPath
    $acl.SetAccessRuleProtection($true, $false)   # disable inheritance
    $owner = New-Object System.Security.Principal.NTAccount($env:USERDOMAIN, $env:USERNAME)
    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        $owner, 'Read,Write', 'Allow'
    )
    $acl.SetAccessRule($rule)
    Set-Acl -Path $secretsPath -AclObject $acl
    Write-Host "ACL: lecture seule pour $($env:USERDOMAIN)\$($env:USERNAME)" -ForegroundColor DarkGray
} catch {
    Write-Host "(Impossible de durcir l'ACL, pas grave: $($_.Exception.Message))" -ForegroundColor DarkGray
}

Write-Host ''
Write-Host "OK -> $secretsPath" -ForegroundColor Green
Write-Host ''
Write-Host 'Maintenant tu peux supprimer ces champs du config.json:' -ForegroundColor Yellow
Write-Host '  orthancPassword, cfAccessClientId, cfAccessClientSecret'
Write-Host '(le script import-dicom.ps1 lit les versions chiffrees depuis config.secrets.dpapi.json)'
Write-Host ''
