---
users:
  admin@example.com:
    displayname: "PACS Administrator"
    password: "$argon2id$v=19$m=65536,t=3,p=4$cV4zooAU6KZ0ekOPvt3Vaw$ucm+1skyO16+X6mLhzhabvrDjLf26r6dGKLow01aqPQ"
    email: admin@example.com
    groups:
      - admin
      
  doctor@example.com:
    displayname: "Medical Doctor"
    password: "$argon2id$v=19$m=65536,t=3,p=4$5s3dADvwo2/774m/e+Odqg$0Ac+u23mUeroCYI489wc7oW4f0yA4s1gGWmaSCqPoZI"
    email: doctor@example.com
    groups:
      - doctor
      
  external@example.com:
    displayname: "External User"
    password: "$argon2id$v=19$m=65536,t=3,p=4$PVSjXvKO2cR/XgVcu1aKQw$AKFOE0jOMcEksdkhslxaMl9sWmTouM/C7g0WbJis+hM"
    email: external@example.com
    groups:
      - external
