---
users:
  admin@example.com:
    displayname: "Administrateur PACS"
    password: "$argon2id$v=19$m=65536,t=3,p=4$UdZSJePOoejeJKlqYDT8AQ$0c9SgJ4ShPOQy0mzwxZOlBy0IMYfEn5oWmK3HeqpQLo"
    email: admin@example.com
    groups:
      - admin
      
  doctor@example.com:
    displayname: "Médecin"
    password: "$argon2id$v=19$m=65536,t=3,p=4$yeaaAby0tZzKjYveNi6zCA$G55AGJYIHuZSTCa0o07AKOXekIfMpmrPH7jYzKNt7yA"
    email: doctor@example.com
    groups:
      - doctor
      
  external@example.com:
    displayname: "Utilisateur Externe"
    password: "$argon2id$v=19$m=65536,t=3,p=4$G1xhCtTUoT9O1j08awoA7w$uNZtzlez8t6RgoQOiqLNBY+ayABBrtQ5JO8Zt2GAAV0"
    email: external@example.com
    groups:
      - external
