---
users:
  cuffel.gregory@gmail.com:
    displayname: "PACS Administrator"
    password: "$argon2id$v=19$m=65536,t=3,p=4$rJnIL1OY2KT7dAXq9axIMQ$rbuYdMp35Zu9qJ4kra/MAu6RZ4iNqYF4vNAeJOEPgXM"
    email: cuffel.gregory@gmail.com
    groups:
      - admin
      
  docteur@yokoinc.ovh:
    displayname: "Medical Doctor"
    password: "$argon2id$v=19$m=65536,t=3,p=4$YsjeDE9tUfvm0lrKeodVWQ$DlYhHulJEMIOjLwHDZZzkqui4wUacVDkShlEb1voccM"
    email: docteur@yokoinc.ovh
    groups:
      - doctor
      
  externe@yokoinc.ovh:
    displayname: "External User"
    password: "$argon2id$v=19$m=65536,t=3,p=4$Lg1eLUzoYAPspvkd4mVNEw$zj2bo2xg9oeRYKaCr+MyWUJN9+YjN7zmLdcRn0YsdF0"
    email: externe@yokoinc.ovh
    groups:
      - external
