#!/usr/bin/env bash
# =============================================================================
# ORTHANC-AUTHELIA — Reset an installation
# =============================================================================
# Puts the directory back in the state of a fresh clone: containers, volumes
# (hence every stored image), generated configuration and secrets. The next
# ./bootstrap.sh then starts from scratch.
#
# Usage:
#   ./scripts/reset-install.sh          # asks for confirmation
#   ./scripts/reset-install.sh --yes    # no question (CI)
#
# Why a script rather than the `rm -rf` this file replaces: at startup Authelia
# takes ownership of its own configuration directory and closes it
# (root, drwx------). An ordinary account can then no longer delete
# users_database.yml or db.sqlite3 there -- `rm` says "Permission denied" in
# the middle of an otherwise successful command, which is easy to miss. The
# installation looks erased while the previous administrator account is still
# there: the setup wizard stays closed (404) with no account to sign in with.
# Found on a real machine on 2026-09-25, twice in a row. Everything this script
# cannot delete itself, it deletes through a throwaway container running as
# root.
# =============================================================================

set -euo pipefail

info()  { printf "\033[36m→\033[0m %s\n" "$*"; }
ok()    { printf "\033[32m✓\033[0m %s\n" "$*"; }
warn()  { printf "\033[33m!\033[0m %s\n" "$*"; }
err()   { printf "\033[31m✗\033[0m %s\n" "$*" >&2; }

cd "$(dirname "$0")/.."

if [[ ! -f bootstrap.sh ]]; then
    err "Run this script from the installation directory (bootstrap.sh not found)."
    exit 1
fi

OUI=0
[[ "${1:-}" == "--yes" ]] && OUI=1

if [[ $OUI -eq 0 ]]; then
    warn "This deletes EVERY stored image, every account and every secret"
    warn "of this installation ($PWD)."
    printf "Type 'reset' to confirm: "
    read -r reponse
    if [[ "$reponse" != "reset" ]]; then
        info "Nothing done."
        exit 0
    fi
fi

# ---------------------------------------------------------------------------
# Containers and volumes
# ---------------------------------------------------------------------------
# `down -v` removes the named volumes declared by the compose file. It is the
# only command that does: `docker system prune --volumes` never touches a named
# volume, only anonymous ones. Without the compose file (already deleted by a
# previous attempt) the volumes are removed by name.
if [[ -f docker-compose.yml ]]; then
    info "Stopping the stack and deleting its volumes"
    docker compose down -v >/dev/null 2>&1 || true
fi
RESTANTS=$(docker volume ls --format '{{.Name}}' 2>/dev/null \
    | grep -E '^orthanc_(redis_data|postgres_data|nginx_ssl)$' || true)
if [[ -n $RESTANTS ]]; then
    info "Deleting the remaining volumes"
    # shellcheck disable=SC2086
    docker volume rm $RESTANTS >/dev/null 2>&1 || true
fi

# ---------------------------------------------------------------------------
# Generated files
# ---------------------------------------------------------------------------
# Everything listed here is regenerated by bootstrap.sh. Nothing tracked by git
# is touched: the .example files, which are the actual source, stay put.
#
# db.sqlite3 deserves its place in the list. It holds only the sessions, the
# 2FA registrations and the brute-force counters -- the accounts live in
# users_database.yml -- but it is encrypted with a key drawn in .env. Kept next
# to a new .env, it makes Authelia refuse to start for good:
#   "the configured encryption key does not appear to be valid for this
#    database"
A_SUPPRIMER=(
    .env
    docker-compose.yml
    data/admin-backups
    services/authelia/config/configuration.yml
    services/authelia/config/users_database.yml
    services/authelia/config/users_database.yml.lock
    services/authelia/config/db.sqlite3
    services/authelia/config/notification.txt
    services/orthanc/config/orthanc.json
)

# Databases left behind by a previous reset (bootstrap.sh moves aside any
# Authelia database whose encryption key has gone). Unreadable by design, they
# serve nothing here.
for f in services/authelia/config/db.sqlite3.orpheline-*; do
    [[ -e $f ]] && A_SUPPRIMER+=("$f")
done

info "Deleting the generated configuration"
RECALCITRANTS=()
for f in "${A_SUPPRIMER[@]}"; do
    [[ -e $f ]] || continue
    rm -rf "$f" 2>/dev/null || RECALCITRANTS+=("$f")
done

# What the account cannot delete is deleted as root, from a container that
# mounts the directory.
#
# Which image: any local one that offers a shell. --user 0 and --entrypoint sh
# are not optional -- an application image (ours, for one) starts its server
# under an unprivileged account, and `docker run image sh -c …` then passes
# "sh -c …" as arguments to that server rather than running a shell. Tried on
# 2026-09-25: the reset reported success having deleted nothing. Candidates
# are therefore tried in order, and the result is CHECKED, not assumed.
nettoyer_en_root() {
    local img
    for img in $(images_candidates); do
        if docker run --rm --user 0 --entrypoint sh \
                -v "$PWD/services/authelia/config:/authelia" \
                -v "$PWD/services/orthanc/config:/orthanc" \
                -v "$PWD/data:/data" \
                "$img" -c '
                    rm -rf /authelia/configuration.yml /authelia/users_database.yml \
                           /authelia/users_database.yml.lock /authelia/db.sqlite3 \
                           /authelia/db.sqlite3.orpheline-* \
                           /authelia/notification.txt \
                           /orthanc/orthanc.json /data/admin-backups
                    # The directory itself stays closed (root, drwx------) once
                    # Authelia has been through it: bootstrap.sh could not write
                    # the new configuration there. Handing it back is part of
                    # the reset.
                    chmod 755 /authelia
                    exit 0
                ' >/dev/null 2>&1; then
            info "  cleaned through $img"
            return 0
        fi
    done
    return 1
}

# The stack's own base images (redis, postgres, alpine…) come first: they carry
# a shell and no entrypoint of their own. alpine:3.20 closes the list and is
# pulled only if the machine holds nothing usable.
images_candidates() {
    local locales
    locales=$(docker image ls --format '{{.Repository}}:{{.Tag}}' 2>/dev/null | grep -v '<none>' || true)
    printf '%s\n' "$locales" | grep -E '^(alpine|busybox|redis|postgres|nginx|authelia/authelia)' || true
    printf '%s\n' "$locales"
    printf 'alpine:3.20\n'
}

if [[ ${#RECALCITRANTS[@]} -gt 0 ]] || [[ -d services/authelia/config && ! -r services/authelia/config ]]; then
    info "Files owned by root: deleting them through a container"
    nettoyer_en_root || warn "No usable image found to clean up as root"
fi

# ---------------------------------------------------------------------------
# What is left
# ---------------------------------------------------------------------------
# `[[ -e $f ]]` is not enough on its own: inside a directory the account cannot
# open, the test is false for a file that is very much there, and the reset
# would announce a success it did not achieve. An unreadable directory is
# therefore a failure in itself -- a successful cleanup reopens it.
RESTE=()
if [[ -d services/authelia/config && ! -r services/authelia/config ]]; then
    RESTE+=("services/authelia/config (directory closed, contents unknown)")
fi
for f in "${A_SUPPRIMER[@]}"; do
    [[ -e $f ]] && RESTE+=("$f")
done
if [[ ${#RESTE[@]} -gt 0 ]]; then
    err "These files could not be deleted:"
    printf '        %s\n' "${RESTE[@]}" >&2
    err "Delete them as administrator, then run ./bootstrap.sh"
    exit 1
fi

ok "Installation reset"
info "Next step:  ./bootstrap.sh"
